mkdir /tmp/keyphrase_model 
python -m nmt.nmt \
	--batch_size=4 \
	--vocab_prefix=/project/data/test_for_keyphrase/voc \
	--train_prefix=/project/data/test_for_keyphrase/train \
	--dev_prefix=/project/data/test_for_keyphrase/validation \
	--test_prefix=/project/data/test_for_keyphrase/test \
	--embed_prefix=/project/data/test_for_keyphrase/embedding \
	--out_dir=/tmp/keyphrase_model \
	--num_train_steps=10000 \
	--steps_per_stats=100 \
	--num_layers=2 \
	--num_units=200 \
	--dropout=0.2 \
	--src_max_len=400 \
	--tgt_max_len=50 \
	--infer_batch_size=2 \
	--num_gpus=1 \
	--src_max_len_infer=400 \
	--tgt_max_len_infer=50 \
	--encoder_type=bi \
	--unit_type=gru \
	--share_vocab